Work_Wave/Controllers/TicketsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Work_Wave.Data;
using Work_Wave.Models;
using Work_Wave.Services.Interfaces;

namespace Work_Wave.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<WaveUser> _userManager;
        private readonly ITTicketService _ticketService;

        public TicketsController(ApplicationDbContext context, UserManager<WaveUser> userManager, ITTicketService ticketService)
        {
            _context = context;
            _userManager = userManager;
            _ticketService = ticketService;
        }


        // GET: Tickets
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Tickets.Include(t => t.Priority).Include(t => t.Support).Include(t => t.Technician);

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Tickets - MY TICKETS
        [Authorize(Roles = "Admin, Manager, Employee")]
        public async Task<IActionResult> MyTickets()
        {
            var applicationDbContext = _context.Tickets.Include(t => t.Priority).Include(t => t.Support).Include(t => t.Technician);

            WaveUser user = await _userManager.GetUserAsync(User);

            List<Ticket> tickets = new List<Ticket>();

            foreach (var t in applicationDbContext)
            {
                if (t.SupportId == user.Id)
                {

                    tickets.Add(t);
                }
                else if (t.TechnicianId == user.Id)
                {
                    tickets.Add(t);
                }
            }
            return View(tickets);
        }

        // GET: Tickets/Details/5
        [Authorize(Roles = "Admin, Manager, Employee")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Ticket ticket = await _ticketService.GetTicketByIdAsync(id.Value);

            if (ticket == null)
            {
                return NotFound();
            }

                return View(ticket);
        }

        // GET: Tickets/Create
        [Authorize(Roles = "Admin, Manager, Employee")]
        public async Task<IActionResult> Create()
        {
            ViewData["PriorityId"] = new SelectList(_context.Priorities, "Id", "Name");
            ViewData["TechnicianId"] = new SelectList(_context.Users, "Id", "FullName");
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Manager, Employee")]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,CFirstName,CLastName,CPhone,CAddress,CCity,CState,CZip,Created,Schedule,PriorityId,TechnicianId,SupportId")] Ticket ticket)
        {
            WaveUser user = await _userManager.GetUserAsync(User);

            ticket.SupportId = user.Id;

            ticket.Created = DateTimeOffset.Now;

            _context.Add(ticket);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(MyTickets));

            ViewData["PriorityId"] = new SelectList(_context.Priorities, "Id", "Name", ticket.PriorityId);
            ViewData["TechnicianId"] = new SelectList(_context.Users, "Id", "FullName", ticket.TechnicianId);
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        [Authorize(Roles = "Admin, Manager, Employee")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.FindAsync(id);
            if (ticket == null)
            {
                return NotFound();
            }
            ViewData["PriorityId"] = new SelectList(_context.Priorities, "Id", "Name", ticket.PriorityId);
            ViewData["SupportId"] = new SelectList(_context.Users, "Id", "FullName", ticket.SupportId);
            ViewData["TechnicianId"] = new SelectList(_context.Users, "Id", "FullName", ticket.TechnicianId);
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Manager, Employee")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,CFirstName,CLastName,CPhone,CAddress,CCity,CState,CZip,Created,Schedule,IsArchived,PriorityId,TechnicianId,SupportId")] Ticket ticket)
        {
            if (id != ticket.Id)
            {
                return NotFound();
            }

                try
                {
                    ticket.Created = DateTimeOffset.Now;

                    _context.Update(ticket);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketExists(ticket.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            if (User.IsInRole("Admin"))
            {
                return RedirectToAction(nameof(Index));
            }
            else if ((User.IsInRole("Manager")))
            {
                return RedirectToAction(nameof(Index));
            }
            else
                return RedirectToAction(nameof(MyTickets));

            ViewData["PriorityId"] = new SelectList(_context.Priorities, "Id", "Name", ticket.PriorityId);
            ViewData["SupportId"] = new SelectList(_context.Users, "Id", "FullName", ticket.SupportId);
            ViewData["TechnicianId"] = new SelectList(_context.Users, "Id", "FullName", ticket.TechnicianId);
            return View(ticket);
        }

        // Ticket Comment

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Manager, Employee")]
        public async Task<IActionResult> AddTicketComment([Bind("Id,TicketId,Note,UserId")] Comment comment)
        {
            comment.UserId = _userManager.GetUserId(User);
            comment.Created = DateTimeOffset.Now;


            await _ticketService.AddTicketCommentAsync(comment);

            Ticket ticket = await _ticketService.GetTicketByIdAsync(comment.TicketId);

            ticket.Comments.Add(comment);

            return RedirectToAction("Details", new { id = comment.TicketId });
        }
        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .Include(t => t.Priority)
                .Include(t => t.Support)
                .Include(t => t.Technician)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Manager, Employee")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ticket = await _context.Tickets.FindAsync(id);

            ticket.IsArchived = true;

            _context.Tickets.Update(ticket);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Tickets/Retore/5
        [Authorize(Roles = "Admin, Manager, Employee")]
        public async Task<IActionResult> Restore(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .Include(t => t.Priority)
                .Include(t => t.Support)
                .Include(t => t.Technician)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Restore/5
        [HttpPost, ActionName("Restore")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Manager, Employee")]
        public async Task<IActionResult> RestoreConfirmed(int id)
        {
            var ticket = await _context.Tickets.FindAsync(id);

            ticket.IsArchived = false;

            _context.Tickets.Update(ticket);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketExists(int id)
        {
            return _context.Tickets.Any(e => e.Id == id);
        }
    }
}

Work_Wave/Controllers/UserRolesController.cs
using Microsoft.AspNetCore.Mvc;
using Work_Wave.Services.Interfaces;
using Work_Wave.Models.ViewModels;
using Work_Wave.Models;
using Work_Wave.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace Work_Wave.Controllers
{
    public class UserRolesController : Controller
    {
        private readonly ITRolesService _rolesService;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<WaveUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;



        public UserRolesController(ITRolesService rolesService, ApplicationDbContext context, UserManager<WaveUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _rolesService = rolesService;
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> ManageUserRoles()
        {
            List<ManageUserRolesViewModel> model = new();

            List<WaveUser> users = await _context.Users.ToListAsync();

            foreach(WaveUser user in users)
            {
                ManageUserRolesViewModel viewModel = new();

                viewModel.User = user;

                IEnumerable<string> selected = await _rolesService.GetUserRolesAsync(user);

                viewModel.Roles = new MultiSelectList(await _rolesService.GetRolesAync(), "Name", "Name", selected);

                model.Add(viewModel);
            }


            return View(model);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageUserRoles(ManageUserRolesViewModel member)
        {
            WaveUser waveUser = (await _context.Users.ToListAsync()).FirstOrDefault(u => u.Id == member.User.Id);

            IEnumerable<string> roles = await _rolesService.GetUserRolesAsync(waveUser);

            string userRole = member.SelectedRoles.FirstOrDefault();

            if (!string.IsNullOrEmpty(userRole))
            {
                if(await _rolesService.RemoveUserFromRolesAsync(waveUser, roles))
                {
                    await _rolesService.AddUserToRoleAsync(waveUser, userRole);
                }

            }

            return RedirectToAction(nameof(ManageUserRoles));
        }
    }
}

Work_Wave/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Work_Wave</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Work_Wave.styles.css" asp-append-version="true" />
    <link runat="server" rel="icon" href="~/wave.ico" type="image/ico" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Work Wave</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if(User.IsInRole("Admin")){
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserRoles" asp-action="ManageUserRoles">User Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">All Tickets</a>
                        </li>
                        }
                        else if(User.IsInRole("Manager")){
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">All Tickets</a>
                        </li>
                        }
                        else if (User.IsInRole("Employee")){
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="MyTickets">Tickets</a>
                        </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="card-footer text-muted">
        <div class="container">
            &copy; 2022 - Work Wave
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>